// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy648_HCIfi8j8zuYouus3EROsfn0o5vQ',
    appId: '1:900317748458:web:11c4da22542a3379528b93',
    messagingSenderId: '900317748458',
    projectId: 'message-board-app-ff876',
    authDomain: 'message-board-app-ff876.firebaseapp.com',
    storageBucket: 'message-board-app-ff876.firebasestorage.app',
    measurementId: 'G-G65520H0XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJE7Ig6sSDfkyil-9M06olEb9JtuB0ck',
    appId: '1:900317748458:android:3d982642694e1a88528b93',
    messagingSenderId: '900317748458',
    projectId: 'message-board-app-ff876',
    storageBucket: 'message-board-app-ff876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzkzNmok8hWl36YcLLQZbwsNzT3FdmCrs',
    appId: '1:900317748458:ios:5f5151d3a5b0151b528b93',
    messagingSenderId: '900317748458',
    projectId: 'message-board-app-ff876',
    storageBucket: 'message-board-app-ff876.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzkzNmok8hWl36YcLLQZbwsNzT3FdmCrs',
    appId: '1:900317748458:ios:5f5151d3a5b0151b528b93',
    messagingSenderId: '900317748458',
    projectId: 'message-board-app-ff876',
    storageBucket: 'message-board-app-ff876.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy648_HCIfi8j8zuYouus3EROsfn0o5vQ',
    appId: '1:900317748458:web:fbc7450ecfd7aad2528b93',
    messagingSenderId: '900317748458',
    projectId: 'message-board-app-ff876',
    authDomain: 'message-board-app-ff876.firebaseapp.com',
    storageBucket: 'message-board-app-ff876.firebasestorage.app',
    measurementId: 'G-2BMJ8L07LG',
  );
}
